version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - '1433:1433'
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q "SELECT 1"',
        ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  sqlserverdata:
